---

- name: Hyper - Install terminal
  community.general.homebrew_cask:
    name: hyper
    state: latest

- name: Hyper - Template configuration
  ansible.builtin.template:
    src: .hyper.js
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.hyper.js"
