# tap configuration

tap "homebrew/cask-fonts"
tap "koekeishiya/formulae"

# packages

brew "yabai"
brew "skhd"
brew "borders"

# cask

cask "font-dejavu-sans-mono-nerd-font"
cask "font-hack-nerd-font"
cask "hyper"
cask "tidal"
cask "sonos"
cask "roon"
cask "whatsapp"
cask "google-chrome"
cask "google-drive"
cask "onedrive"
cask "dozer"

# cask "brave-browser"
# cask "arc"
# cask "raycast"
# cask "balenaetcher"
# cask "discord"
# cask "nordvpn"
# cask "marta"
# cask "iina"
# cask "logi-options-plus"
# cask "numi"
# cask "sleek"
# cask "iglance"
# cask "displaylink"
# cask "microsoft-teams"
# cask "google-chat"
# cask "zoom"
# cask "affinity-designer"
# cask "affinity-photo"
# cask "affinity-publisher"
# cask "hashicorp/tap/hashicorp-vagrant"

# mas

# mas "Amphetamine", id: 937984704
